import { Arimo, Roboto } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from './components/Header';


const arimo = Arimo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--primary-font'
})

const roboto = Roboto(
  {
    subsets: ['latin'],
    weight: ['300', '400', '500', '700', '900'],
    variable: '--secondary-font'
  }

)

export const metadata = {
  title: 'Flex2',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${arimo.variable} ${roboto.variable}`}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  )
}
